CREATE DATABASE BAI14
USE BAI14

CREATE TABLE COSO
(
	MACOSO VARCHAR(10) PRIMARY KEY,
	TENCOSO NVARCHAR(100)
)

CREATE TABLE DONVI
(
	MADONVI VARCHAR(10) PRIMARY KEY,
	TENDONVI NVARCHAR(100),
	MACOSO VARCHAR(10),
	CONSTRAINT FK_DONVI_COSO FOREIGN KEY (MACOSO) REFERENCES COSO(MACOSO)
)

CREATE TABLE GV
(
	MAGV VARCHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(100),
	SDT INT,
	GHICHU NVARCHAR(100),
	MADONVI VARCHAR(10),
	CONSTRAINT FK_GV_DONVI FOREIGN KEY (MADONVI) REFERENCES DONVI(MADONVI)
)

INSERT INTO COSO
VALUES
('CS1',N'CƠ SỞ 1'),
('CS2',N'CƠ SỞ 2')


INSERT INTO DONVI
VALUES
('DV1',N'ĐƠN VỊ 1','CS1'),
('DV2',N'ĐƠN VỊ 2','CS2')

INSERT INTO GV
VALUES
('GV1',N'NGUYỄN VĂN A', 0988787212, NULL, 'DV1'),
('GV2',N'NGUYỄN THỊ B', 0988787213, NULL, 'DV2')

DROP PROC SHOW_GV_WITH_HOTEN
GO
CREATE PROC SHOW_GV_WITH_HOTEN
@MADV VARCHAR(10)
AS
SELECT ROW_NUMBER() OVER(ORDER BY HOTEN, MAGV) AS STT, MAGV, HOTEN FROM GV WHERE MADONVI = @MADV

exec SHOW_GV_WITH_HOTEN 'DV1'
GO
CREATE PROC SHOW_GV
@MAGV NVARCHAR(100)
AS
SELECT ROW_NUMBER() OVER(ORDER BY MAGV) AS STT, * FROM GV WHERE MAGV = @MAGV

EXEC SHOW_GV N'NGUYỄN VĂN A'
GO
CREATE PROC SHOW_DV
@MACS VARCHAR(10)
AS
SELECT * FROM DONVI WHERE MACOSO= @MACS

GO
